name: ealib
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
  - dglteam
dependencies:
  - python=3.7
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.0
  - tensorboard
  - tqdm
  - dgl-cuda11.0
  - scikit-learn
  - seaborn
  - pip
  - pip:
      - networkx
      - wandb
      - torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
      - torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
      - torch-cluster -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
      - torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
      - torch-geometric